version: '3'
services:
  database:
    image: mysql:8.0.17
    container_name: mysql
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
