version: '3'
services:
  database:
    image: mysql:8.0.17
    container_name: mysql
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
